//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference {

    [System.Diagnostics.DebuggerStepThroughAttribute ()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute ("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute (Name = "ResultadoEstadoCliente", Namespace = "http://schemas.datacontract.org/2004/07/SGE.Service.Contracts.Data")]
    public partial class ResultadoEstadoCliente : object {

        private int CantidadCreditosActivosField;

        private bool ConsultaValidaField;

        private string ErrorField;

        private bool TieneDeudasField;

        [System.Runtime.Serialization.DataMemberAttribute ()]
        public int CantidadCreditosActivos {
            get {
                return this.CantidadCreditosActivosField;
            }
            set {
                this.CantidadCreditosActivosField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute ()]
        public bool ConsultaValida {
            get {
                return this.ConsultaValidaField;
            }
            set {
                this.ConsultaValidaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute ()]
        public string Error {
            get {
                return this.ErrorField;
            }
            set {
                this.ErrorField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute ()]
        public bool TieneDeudas {
            get {
                return this.TieneDeudasField;
            }
            set {
                this.TieneDeudasField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute ()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute ("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute (Name = "ErrorServicio", Namespace = "http://schemas.datacontract.org/2004/07/SGE.Service.Contracts.Faults")]
    public partial class ErrorServicio : object {

        private string MensajeErrorField;

        [System.Runtime.Serialization.DataMemberAttribute ()]
        public string MensajeError {
            get {
                return this.MensajeErrorField;
            }
            set {
                this.MensajeErrorField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute ()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute ("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute (Name = "ResultadoOperacion", Namespace = "http://schemas.datacontract.org/2004/07/SGE.Service.Contracts.Data")]
    public partial class ResultadoOperacion : object {

        private string ErrorField;

        private bool OperacionValidaField;

        [System.Runtime.Serialization.DataMemberAttribute ()]
        public string Error {
            get {
                return this.ErrorField;
            }
            set {
                this.ErrorField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute ()]
        public bool OperacionValida {
            get {
                return this.OperacionValidaField;
            }
            set {
                this.OperacionValidaField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute ("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.ServiceContractAttribute (Namespace = "http://ISTP1.Service.Contracts.Service", ConfigurationName = "ServiceReference.IServicioPublicoCredito")]
    public interface IServicioPublicoCredito {

        [System.ServiceModel.OperationContractAttribute (Action = "http://ISTP1.Service.Contracts.Service/IServicioPublicoCredito/ObtenerEstadoClien" +
            "te", ReplyAction = "http://ISTP1.Service.Contracts.Service/IServicioPublicoCredito/ObtenerEstadoClien" +
            "teResponse")]
        [System.ServiceModel.FaultContractAttribute (typeof (ServiceReference.ErrorServicio), Action = "http://ISTP1.Service.Contracts.Service/IServicioPublicoCredito/ObtenerEstadoClien" +
            "teErrorServicioFault", Name = "ErrorServicio", Namespace = "http://schemas.datacontract.org/2004/07/SGE.Service.Contracts.Faults")]
        System.Threading.Tasks.Task<ServiceReference.ResultadoEstadoCliente> ObtenerEstadoClienteAsync (string codigoFinanciera, int dni);

        [System.ServiceModel.OperationContractAttribute (Action = "http://ISTP1.Service.Contracts.Service/IServicioPublicoCredito/InformarCreditoOto" +
            "rgado", ReplyAction = "http://ISTP1.Service.Contracts.Service/IServicioPublicoCredito/InformarCreditoOto" +
            "rgadoResponse")]
        [System.ServiceModel.FaultContractAttribute (typeof (ServiceReference.ErrorServicio), Action = "http://ISTP1.Service.Contracts.Service/IServicioPublicoCredito/InformarCreditoOto" +
            "rgadoErrorServicioFault", Name = "ErrorServicio", Namespace = "http://schemas.datacontract.org/2004/07/SGE.Service.Contracts.Faults")]
        System.Threading.Tasks.Task<ServiceReference.ResultadoOperacion> InformarCreditoOtorgadoAsync (string codigoFinanciera, int dni, string identificadorCredito, double montoOtorgado);

        [System.ServiceModel.OperationContractAttribute (Action = "http://ISTP1.Service.Contracts.Service/IServicioPublicoCredito/InformarCreditoFin" +
            "alizado", ReplyAction = "http://ISTP1.Service.Contracts.Service/IServicioPublicoCredito/InformarCreditoFin" +
            "alizadoResponse")]
        [System.ServiceModel.FaultContractAttribute (typeof (ServiceReference.ErrorServicio), Action = "http://ISTP1.Service.Contracts.Service/IServicioPublicoCredito/InformarCreditoFin" +
            "alizadoErrorServicioFault", Name = "ErrorServicio", Namespace = "http://schemas.datacontract.org/2004/07/SGE.Service.Contracts.Faults")]
        System.Threading.Tasks.Task<ServiceReference.ResultadoOperacion> InformarCreditoFinalizadoAsync (string codigoFinanciera, int dni, string identificadorCredito);
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute ("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    public interface IServicioPublicoCreditoChannel : ServiceReference.IServicioPublicoCredito, System.ServiceModel.IClientChannel { }

    [System.Diagnostics.DebuggerStepThroughAttribute ()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute ("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    public partial class ServicioPublicoCreditoClient : System.ServiceModel.ClientBase<ServiceReference.IServicioPublicoCredito>, ServiceReference.IServicioPublicoCredito {

        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint (System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);

        public ServicioPublicoCreditoClient ():
            base (ServicioPublicoCreditoClient.GetDefaultBinding (), ServicioPublicoCreditoClient.GetDefaultEndpointAddress ()) {
                this.Endpoint.Name = EndpointConfiguration.SGEBusService.ToString ();
                ConfigureEndpoint (this.Endpoint, this.ClientCredentials);
            }

        public ServicioPublicoCreditoClient (EndpointConfiguration endpointConfiguration):
            base (ServicioPublicoCreditoClient.GetBindingForEndpoint (endpointConfiguration), ServicioPublicoCreditoClient.GetEndpointAddress (endpointConfiguration)) {
                this.Endpoint.Name = endpointConfiguration.ToString ();
                ConfigureEndpoint (this.Endpoint, this.ClientCredentials);
            }

        public ServicioPublicoCreditoClient (EndpointConfiguration endpointConfiguration, string remoteAddress):
            base (ServicioPublicoCreditoClient.GetBindingForEndpoint (endpointConfiguration), new System.ServiceModel.EndpointAddress (remoteAddress)) {
                this.Endpoint.Name = endpointConfiguration.ToString ();
                ConfigureEndpoint (this.Endpoint, this.ClientCredentials);
            }

        public ServicioPublicoCreditoClient (EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress):
            base (ServicioPublicoCreditoClient.GetBindingForEndpoint (endpointConfiguration), remoteAddress) {
                this.Endpoint.Name = endpointConfiguration.ToString ();
                ConfigureEndpoint (this.Endpoint, this.ClientCredentials);
            }

        public ServicioPublicoCreditoClient (System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress):
            base (binding, remoteAddress) { }

        public System.Threading.Tasks.Task<ServiceReference.ResultadoEstadoCliente> ObtenerEstadoClienteAsync (string codigoFinanciera, int dni) {
            return base.Channel.ObtenerEstadoClienteAsync (codigoFinanciera, dni);
        }

        public System.Threading.Tasks.Task<ServiceReference.ResultadoOperacion> InformarCreditoOtorgadoAsync (string codigoFinanciera, int dni, string identificadorCredito, double montoOtorgado) {
            return base.Channel.InformarCreditoOtorgadoAsync (codigoFinanciera, dni, identificadorCredito, montoOtorgado);
        }

        public System.Threading.Tasks.Task<ServiceReference.ResultadoOperacion> InformarCreditoFinalizadoAsync (string codigoFinanciera, int dni, string identificadorCredito) {
            return base.Channel.InformarCreditoFinalizadoAsync (codigoFinanciera, dni, identificadorCredito);
        }

        public virtual System.Threading.Tasks.Task OpenAsync () {
            return System.Threading.Tasks.Task.Factory.FromAsync (((System.ServiceModel.ICommunicationObject) (this)).BeginOpen (null, null), new System.Action<System.IAsyncResult> (((System.ServiceModel.ICommunicationObject) (this)).EndOpen));
        }

        public virtual System.Threading.Tasks.Task CloseAsync () {
            return System.Threading.Tasks.Task.Factory.FromAsync (((System.ServiceModel.ICommunicationObject) (this)).BeginClose (null, null), new System.Action<System.IAsyncResult> (((System.ServiceModel.ICommunicationObject) (this)).EndClose));
        }

        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint (EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.SGEBusService)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding ();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException (string.Format ("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }

        private static System.ServiceModel.EndpointAddress GetEndpointAddress (EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.SGEBusService)) {
                return new System.ServiceModel.EndpointAddress ("http://ds.dyndns.org:9000/ServicioPublicoCredito");
            }
            throw new System.InvalidOperationException (string.Format ("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }

        private static System.ServiceModel.Channels.Binding GetDefaultBinding () {
            return ServicioPublicoCreditoClient.GetBindingForEndpoint (EndpointConfiguration.SGEBusService);
        }

        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress () {
            return ServicioPublicoCreditoClient.GetEndpointAddress (EndpointConfiguration.SGEBusService);
        }

        public enum EndpointConfiguration {

            SGEBusService,
        }
    }
}